FROM nginx
MAINTAINER ashutoshh
COPY  index.html  /usr/share/nginx/html/index.html
COPY webapp.png  /usr/share/nginx/html/webapp.png
EXPOSE 80
# if u don't write cmd or entrypoint then whatever from Image 
# cmd / entrypoint will be inherited 